/**
 * Alpha Vantage API endpoint definitions.
 * These are the raw API endpoint strings used to communicate with the Alpha Vantage API.
 */
export enum AlphaVantageEndpoint {
  // Time Series
  TIME_SERIES_INTRADAY = 'TIME_SERIES_INTRADAY',
  TIME_SERIES_DAILY = 'TIME_SERIES_DAILY',
  TIME_SERIES_DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED',
  TIME_SERIES_WEEKLY = 'TIME_SERIES_WEEKLY',
  TIME_SERIES_WEEKLY_ADJUSTED = 'TIME_SERIES_WEEKLY_ADJUSTED',
  TIME_SERIES_MONTHLY = 'TIME_SERIES_MONTHLY',
  TIME_SERIES_MONTHLY_ADJUSTED = 'TIME_SERIES_MONTHLY_ADJUSTED',
  
  // Stock Quotes
  GLOBAL_QUOTE = 'GLOBAL_QUOTE',
  
  // Company Information
  OVERVIEW = 'OVERVIEW',
  EARNINGS = 'EARNINGS',
  INCOME_STATEMENT = 'INCOME_STATEMENT',
  BALANCE_SHEET = 'BALANCE_SHEET',
  CASH_FLOW = 'CASH_FLOW',
  
  // Technical Indicators
  SMA = 'SMA',
  EMA = 'EMA',
  RSI = 'RSI',
  MACD = 'MACD',
  BBANDS = 'BBANDS',
  
  // Forex & Crypto
  CURRENCY_EXCHANGE_RATE = 'CURRENCY_EXCHANGE_RATE',
  FX_INTRADAY = 'FX_INTRADAY',
  FX_DAILY = 'FX_DAILY',
  FX_WEEKLY = 'FX_WEEKLY',
  FX_MONTHLY = 'FX_MONTHLY',
  CRYPTO_INTRADAY = 'CRYPTO_INTRADAY',
  DIGITAL_CURRENCY_DAILY = 'DIGITAL_CURRENCY_DAILY',
  DIGITAL_CURRENCY_WEEKLY = 'DIGITAL_CURRENCY_WEEKLY',
  DIGITAL_CURRENCY_MONTHLY = 'DIGITAL_CURRENCY_MONTHLY',
  
  // Economic Indicators
  REAL_GDP = 'REAL_GDP',
  REAL_GDP_PER_CAPITA = 'REAL_GDP_PER_CAPITA',
  INFLATION = 'INFLATION',
  FEDERAL_FUNDS_RATE = 'FEDERAL_FUNDS_RATE',
  
  // Sectors
  SECTOR = 'SECTOR',
}
