import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

interface EnrichedSymbol {
  symbol: string;
  etfs: string[];
}

function loadEnrichedSymbols(path: string): EnrichedSymbol[] {
  const raw = readFileSync(path, 'utf8');
  const parsed = JSON.parse(raw) as unknown;
  if (!Array.isArray(parsed)) {
    throw new Error(`Expected array in ${path}`);
  }
  return parsed as EnrichedSymbol[];
}

function main(): void {
  // Repo root (two levels up from functions/scripts)
  const root = resolve(__dirname, '..', '..');

  const spyQqqPath = resolve(root, 'bulk-import.enriched_spy-qqq.json');
  const xlPath = resolve(root, 'bulk-import.enriched_XL-non-spy-qqq.json');

  const spyQqq = loadEnrichedSymbols(spyQqqPath);
  const xlOnly = loadEnrichedSymbols(xlPath);

  const etfToSymbols = new Map<string, Set<string>>();

  const index = (rows: EnrichedSymbol[]) => {
    for (const row of rows) {
      const sym = row.symbol?.trim();
      if (!sym) continue;
      const etfs = Array.isArray(row.etfs) ? row.etfs : [];
      for (const etf of etfs) {
        const key = etf.trim();
        if (!key) continue;
        if (!etfToSymbols.has(key)) {
          etfToSymbols.set(key, new Set());
        }
        etfToSymbols.get(key)!.add(sym);
      }
    }
  };

  index(spyQqq);
  index(xlOnly);

  const ETF_PRIORITY: string[] = [
    'SPY',
    'QQQ',
    // Sector / factor ETFs (order is intentional for RS baselines)
    'XBI',
    'XLC',
    'XLE',
    'XLF',
    'XLI',
    'XLK',
    'XLU',
    'XLV',
    'XLY',
    'XME',
    'XSD',
  ];

  const master: string[] = [];
  const pushUnique = (sym: string) => {
    if (!sym) return;
    if (!master.includes(sym)) master.push(sym);
  };

  // 1) Baseline ETFs themselves first, in configured order
  for (const etf of ETF_PRIORITY) {
    pushUnique(etf);
  }

  // 2) Constituents for each ETF, sorted alphabetically for determinism
  for (const etf of ETF_PRIORITY) {
    const set = etfToSymbols.get(etf);
    if (!set) continue;
    const symbols = Array.from(set).sort();
    for (const sym of symbols) {
      pushUnique(sym);
    }
  }

  const outPath = resolve(root, 'functions', 'src', 'v2', 'alpha-vantage', 'data', 'ts-master-order.ts');
  mkdirSync(dirname(outPath), { recursive: true });

  const header =
    `// AUTO-GENERATED by functions/scripts/generate-ts-master-order.ts\n` +
    `// Source JSON: bulk-import.enriched_spy-qqq.json, bulk-import.enriched_XL-non-spy-qqq.json\n` +
    `// Do not edit this file by hand.\n\n`;

  const bodyLines = master.map((s) => `  '${s}',`);
  const body =
    `export const TIME_SERIES_MASTER_SYMBOL_ORDER: string[] = [\n` +
    bodyLines.join('\n') +
    `\n];\n`;

  writeFileSync(outPath, header + body, 'utf8');

  // eslint-disable-next-line no-console
  console.log(`Wrote ${master.length} symbols to ${outPath}`);
}

main();
