// Benzinga News Channels Enum, Interface, Objects, and Lookup Map
// Generated from https://www.benzinga.com/api/v2/channels

export interface BzNewsChannelItem {
  id: number;
  parent: number;
  channel: string;
  weight: number;
}

export enum BzNewsChannel {
  AFTER_HOURS_CENTER = 'after-hours-center',
  ANALYST_COLOR = 'analyst-color',
  ANALYST_RATINGS = 'analyst-ratings',
  ASIA = 'asia',
  ASSET_SALES = 'asset-sales',
  BINARY_OPTIONS = 'binary-options',
  BIOTECH = 'biotech',
  BONDS = 'bonds',
  BROAD_US_EQUITY_ETFS = 'broad-us-equity-etfs',
  BUYBACKS = 'buybacks',
  CANNABIS = 'cannabis',
  COMMODITIES = 'commodities',
  CONTRACTS = 'contracts',
  CROWDSOURCING = 'crowdsourcing',
  CRYPTOCURRENCY = 'cryptocurrency',
  CURRENCY_ETFS = 'currency-etfs',
  DIVIDENDS = 'dividends',
  DOWNGRADES = 'downgrades',
  EARNINGS = 'earnings',
  EARNINGS_BEATS = 'earnings-beats',
  EARNINGS_MISSES = 'earnings-misses',
  ECON_NUMBERS = 'econ-nums',
  ECONOMICS = 'economics',
  EDUCATION = 'education',
  EMERGING_MARKET_ETFS = 'emerging-market-etfs',
  EMERGING_MARKETS = 'emerging-markets',
  ENTERTAINMENT = 'entertainment',
  ENTREPRENEURSHIP = 'entrepreneurship',
  EQUITIES = 'equities',
  ESG = 'esg',
  ETFS = 'etfs',
  EUROZONE = 'eurozone',
  EVENTS = 'events',
  EXCLUSIVES = 'exclusives',
  FDA = 'fda',
  FEDERAL_RESERVE = 'federal-reserve',
  FINANCIAL_ADVISORS = 'financial-advisors',
  FINANCING = 'financing',
  FINTECH = 'fintech',
  FOREX = 'forex',
  FUTURES = 'futures',
  GAMING = 'gaming',
  GENERAL = 'general',
  GLOBAL = 'global',
  GOVERNMENT = 'government',
  GUIDANCE = 'guidance',
  HEALTH_CARE = 'health-care',
  HEDGE_FUNDS = 'hedge-funds',
  HOT = 'hot',
  INITIATION = 'initiation',
  INSIDER_TRADES = 'insider-trades',
  INSURANCE = 'insurance',
  INTERVIEW = 'interview',
  INTRADAY_UPDATE = 'intraday-update',
  IPOS = 'ipos',
  LARGE_CAP = 'large-cap',
  LATIN_AMERICA = 'latin-america',
  LEGAL = 'legal',
  LONG_IDEAS = 'long-ideas',
  MA = 'ma',
  MACRO_ECONOMIC_EVENTS = 'macro-economic-events',
  MACRO_NOTIFICATION = 'macro-notification',
  MANAGEMENT = 'management',
  MARKET_SUMMARY = 'market-summary',
  MARKET_MOVING_EXCLUSIVES = 'market-moving-exclusives',
  MARKETS = 'markets',
  MEDIA = 'media',
  MID_CAP = 'mid-cap',
  MOVERS = 'movers',
  MOVERS_SHAKERS = 'movers-shakers',
  MUTUAL_FUNDS = 'mutual-funds',
  NEW_ETFS = 'new-etfs',
  NEWS = 'news',
  OFFERINGS = 'offerings',
  OPINION = 'opinion',
  OPTIONS = 'options',
  PENNY_STOCKS = 'penny-stocks',
  PERSONAL_FINANCE = 'personal-finance',
  POLITICS = 'politics',
  PRE_MARKET_OUTLOOK = 'pre-market-outlook',
  PRESS_RELEASES = 'press-releases',
  PREVIEWS = 'previews',
  PRICE_TARGET = 'price-target',
  PSYCHEDELICS = 'psychedelics',
  PSYCHOLOGY = 'psychology',
  REAL_ESTATE = 'real-estate',
  REGULATIONS = 'regulations',
  REIT = 'reit',
  REITERATION = 'reiteration',
  RESTAURANTS = 'restaurants',
  RETAIL_SALES = 'retail-sales',
  REVIEWS = 'reviews',
  RUMORS = 'rumors',
  SEC = 'sec',
  SECTOR_ETFS = 'sector-etfs',
  SHORT_IDEAS = 'short-ideas',
  SHORT_SELLERS = 'short-sellers',
  SIGNALS = 'signals',
  SMALL_BUSINESS = 'small-business',
  SMALL_CAP = 'small-cap',
  SMALL_CAP_ANALYSIS = 'small-cap-analysis',
  SOCIAL_MEDIA = 'social-media',
  SPACE = 'space',
  SPECIALTY_ETFS = 'specialty-etfs',
  SPORTS = 'sports',
  SPORTS_BETTING = 'sports-betting',
  STARTUPS = 'startups',
  STOCK_SPLIT = 'stock-split',
  SUCCESS_STORIES = 'success-stories',
  TECH = 'tech',
  TECHNICALS = 'technicals',
  TERMINATION = 'termination',
  TOP_STORIES = 'top-stories',
  TOPICS = 'topics',
  TRADING_IDEAS = 'trading-ideas',
  TRAVEL = 'travel',
  TREASURIES = 'treasuries',
  UPGRADES = 'upgrades',
  WIIM = 'wiim',
}

// Individual channel objects
export const BZ_NEWS_CHANNELS: Record<BzNewsChannel, BzNewsChannelItem> = {
  [BzNewsChannel.AFTER_HOURS_CENTER]: { id: 26, parent: 0, channel: 'After-Hours Center', weight: 38 },
  [BzNewsChannel.ANALYST_COLOR]: { id: 68, parent: 67, channel: 'Analyst Color', weight: 0 },
  [BzNewsChannel.ANALYST_RATINGS]: { id: 67, parent: 0, channel: 'Analyst Ratings', weight: 48 },
  [BzNewsChannel.ASIA]: { id: 831968, parent: 2, channel: 'Asia', weight: 0 },
  [BzNewsChannel.ASSET_SALES]: { id: 34992, parent: 57, channel: 'Asset Sales', weight: 9 },
  [BzNewsChannel.BINARY_OPTIONS]: { id: 132653, parent: 2, channel: 'Binary Options', weight: 0 },
  [BzNewsChannel.BIOTECH]: { id: 19868, parent: 18467, channel: 'Biotech', weight: 0 },
  [BzNewsChannel.BONDS]: { id: 85, parent: 2, channel: 'Bonds', weight: 1 },
  [BzNewsChannel.BROAD_US_EQUITY_ETFS]: { id: 50, parent: 47, channel: 'Broad U.S. Equity ETFs', weight: 1 },
  [BzNewsChannel.BUYBACKS]: { id: 63, parent: 57, channel: 'Buybacks', weight: 8 },
  [BzNewsChannel.CANNABIS]: { id: 123430, parent: 2, channel: 'Cannabis', weight: 0 },
  [BzNewsChannel.COMMODITIES]: { id: 36240, parent: 2, channel: 'Commodities', weight: 5 },
  [BzNewsChannel.CONTRACTS]: { id: 87, parent: 57, channel: 'Contracts', weight: 6 },
  [BzNewsChannel.CROWDSOURCING]: { id: 38928, parent: 18467, channel: 'Crowdsourcing', weight: 11 },
  [BzNewsChannel.CRYPTOCURRENCY]: { id: 135733, parent: 2, channel: 'Cryptocurrency', weight: 0 },
  [BzNewsChannel.CURRENCY_ETFS]: { id: 54, parent: 47, channel: 'Currency ETFs', weight: 5 },
  [BzNewsChannel.DIVIDENDS]: { id: 41, parent: 22, channel: 'Dividends', weight: 2 },
  [BzNewsChannel.DOWNGRADES]: { id: 70, parent: 67, channel: 'Downgrades', weight: 3 },
  [BzNewsChannel.EARNINGS]: { id: 16888, parent: 57, channel: 'Earnings', weight: 0 },
  [BzNewsChannel.EARNINGS_BEATS]: { id: 862672, parent: 16888, channel: 'Earnings Beats', weight: 0 },
  [BzNewsChannel.EARNINGS_MISSES]: { id: 862673, parent: 16888, channel: 'Earnings Misses', weight: 0 },
  [BzNewsChannel.ECON_NUMBERS]: { id: 35794, parent: 57, channel: 'Econ #s', weight: 21 },
  [BzNewsChannel.ECONOMICS]: { id: 17375, parent: 0, channel: 'Economics', weight: 25 },
  [BzNewsChannel.EDUCATION]: { id: 125556, parent: 18467, channel: 'Education', weight: 1 },
  [BzNewsChannel.EMERGING_MARKET_ETFS]: { id: 55, parent: 47, channel: 'Emerging Market ETFs', weight: 4 },
  [BzNewsChannel.EMERGING_MARKETS]: { id: 125558, parent: 2, channel: 'Emerging Markets', weight: 2 },
  [BzNewsChannel.ENTERTAINMENT]: { id: 831970, parent: 18467, channel: 'Entertainment', weight: 0 },
  [BzNewsChannel.ENTREPRENEURSHIP]: { id: 17412, parent: 18467, channel: 'Entrepreneurship', weight: 2 },
  [BzNewsChannel.EQUITIES]: { id: 24769, parent: 2, channel: 'Equities', weight: 0 },
  [BzNewsChannel.ESG]: { id: 831969, parent: 2, channel: 'ESG', weight: 0 },
  [BzNewsChannel.ETFS]: { id: 47, parent: 0, channel: 'ETFs', weight: 76 },
  [BzNewsChannel.EUROZONE]: { id: 125557, parent: 2, channel: 'Eurozone', weight: 3 },
  [BzNewsChannel.EVENTS]: { id: 29618, parent: 57, channel: 'Events', weight: 19 },
  [BzNewsChannel.EXCLUSIVES]: { id: 145889, parent: 0, channel: 'Exclusives', weight: 32 },
  [BzNewsChannel.FDA]: { id: 59, parent: 57, channel: 'FDA', weight: 11 },
  [BzNewsChannel.FEDERAL_RESERVE]: { id: 125743, parent: 0, channel: 'Federal Reserve', weight: 26 },
  [BzNewsChannel.FINANCIAL_ADVISORS]: { id: 38929, parent: 17834, channel: 'Financial Advisors', weight: 0 },
  [BzNewsChannel.FINANCING]: { id: 34989, parent: 57, channel: 'Financing', weight: 4 },
  [BzNewsChannel.FINTECH]: { id: 144421, parent: 0, channel: 'Fintech', weight: 0 },
  [BzNewsChannel.FOREX]: { id: 3, parent: 2, channel: 'Forex', weight: 7 },
  [BzNewsChannel.FUTURES]: { id: 86, parent: 2, channel: 'Futures', weight: 4 },
  [BzNewsChannel.GAMING]: { id: 831973, parent: 18467, channel: 'Gaming', weight: 0 },
  [BzNewsChannel.GENERAL]: { id: 18467, parent: 0, channel: 'General', weight: 83 },
  [BzNewsChannel.GLOBAL]: { id: 17027, parent: 57, channel: 'Global', weight: 20 },
  [BzNewsChannel.GOVERNMENT]: { id: 26029, parent: 0, channel: 'Government', weight: 0 },
  [BzNewsChannel.GUIDANCE]: { id: 16889, parent: 57, channel: 'Guidance', weight: 1 },
  [BzNewsChannel.HEALTH_CARE]: { id: 140295, parent: 18467, channel: 'Health Care', weight: 3 },
  [BzNewsChannel.HEDGE_FUNDS]: { id: 44, parent: 18467, channel: 'Hedge Funds', weight: 4 },
  [BzNewsChannel.HOT]: { id: 38925, parent: 0, channel: 'Hot', weight: 35 },
  [BzNewsChannel.INITIATION]: { id: 71, parent: 67, channel: 'Initiation', weight: 5 },
  [BzNewsChannel.INSIDER_TRADES]: { id: 62, parent: 57, channel: 'Insider Trades', weight: 14 },
  [BzNewsChannel.INSURANCE]: { id: 26330, parent: 0, channel: 'Insurance', weight: 75 },
  [BzNewsChannel.INTERVIEW]: { id: 125566, parent: 0, channel: 'Interview', weight: 74 },
  [BzNewsChannel.INTRADAY_UPDATE]: { id: 25, parent: 0, channel: 'Intraday Update', weight: 37 },
  [BzNewsChannel.IPOS]: { id: 34991, parent: 57, channel: 'IPOs', weight: 17 },
  [BzNewsChannel.LARGE_CAP]: { id: 831976, parent: 57, channel: 'Large Cap', weight: 0 },
  [BzNewsChannel.LATIN_AMERICA]: { id: 831967, parent: 2, channel: 'Latin America', weight: 0 },
  [BzNewsChannel.LEGAL]: { id: 29619, parent: 57, channel: 'Legal', weight: 12 },
  [BzNewsChannel.LONG_IDEAS]: { id: 38, parent: 22, channel: 'Long Ideas', weight: 0 },
  [BzNewsChannel.MA]: { id: 64, parent: 0, channel: 'M&A', weight: 0 },
  [BzNewsChannel.MACRO_ECONOMIC_EVENTS]: { id: 862546, parent: 17375, channel: 'Macro Economic Events', weight: 0 },
  [BzNewsChannel.MACRO_NOTIFICATION]: { id: 927213, parent: 18467, channel: 'Macro Notification', weight: 0 },
  [BzNewsChannel.MANAGEMENT]: { id: 60, parent: 57, channel: 'Management', weight: 13 },
  [BzNewsChannel.MARKET_SUMMARY]: { id: 927212, parent: 18467, channel: 'Market Summary', weight: 0 },
  [BzNewsChannel.MARKET_MOVING_EXCLUSIVES]: { id: 165347, parent: 0, channel: 'Market-Moving Exclusives', weight: 31 },
  [BzNewsChannel.MARKETS]: { id: 2, parent: 0, channel: 'Markets', weight: 39 },
  [BzNewsChannel.MEDIA]: { id: 5, parent: 0, channel: 'Media', weight: 58 },
  [BzNewsChannel.MID_CAP]: { id: 831977, parent: 57, channel: 'Mid Cap', weight: 0 },
  [BzNewsChannel.MOVERS]: { id: 24, parent: 22, channel: 'Movers', weight: 56 },
  [BzNewsChannel.MOVERS_SHAKERS]: { id: 34, parent: 18467, channel: 'Movers & Shakers', weight: 5 },
  [BzNewsChannel.MUTUAL_FUNDS]: { id: 17043, parent: 2, channel: 'Mutual Funds', weight: 0 },
  [BzNewsChannel.NEW_ETFS]: { id: 40009, parent: 47, channel: 'New ETFs', weight: 3 },
  [BzNewsChannel.NEWS]: { id: 57, parent: 0, channel: 'News', weight: 0 },
  [BzNewsChannel.OFFERINGS]: { id: 65, parent: 57, channel: 'Offerings', weight: 5 },
  [BzNewsChannel.OPINION]: { id: 146540, parent: 0, channel: 'Opinion', weight: 23 },
  [BzNewsChannel.OPTIONS]: { id: 16784, parent: 2, channel: 'Options', weight: 6 },
  [BzNewsChannel.PENNY_STOCKS]: { id: 22681, parent: 2, channel: 'Penny Stocks', weight: 0 },
  [BzNewsChannel.PERSONAL_FINANCE]: { id: 17834, parent: 0, channel: 'Personal Finance', weight: 64 },
  [BzNewsChannel.POLITICS]: { id: 16779, parent: 18467, channel: 'Politics', weight: 6 },
  [BzNewsChannel.PRE_MARKET_OUTLOOK]: { id: 23, parent: 0, channel: 'Pre-Market Outlook', weight: 36 },
  [BzNewsChannel.PRESS_RELEASES]: { id: 16777, parent: 0, channel: 'Press Releases', weight: 75 },
  [BzNewsChannel.PREVIEWS]: { id: 39090, parent: 22, channel: 'Previews', weight: 5 },
  [BzNewsChannel.PRICE_TARGET]: { id: 72, parent: 67, channel: 'Price Target', weight: 4 },
  [BzNewsChannel.PSYCHEDELICS]: { id: 748887, parent: 2, channel: 'Psychedelics', weight: 0 },
  [BzNewsChannel.PSYCHOLOGY]: { id: 37760, parent: 18467, channel: 'Psychology', weight: 7 },
  [BzNewsChannel.REAL_ESTATE]: { id: 142057, parent: 0, channel: 'Real Estate', weight: 97 },
  [BzNewsChannel.REGULATIONS]: { id: 144213, parent: 26029, channel: 'Regulations', weight: 0 },
  [BzNewsChannel.REIT]: { id: 142059, parent: 142057, channel: 'REIT', weight: 0 },
  [BzNewsChannel.REITERATION]: { id: 39823, parent: 67, channel: 'Reiteration', weight: 6 },
  [BzNewsChannel.RESTAURANTS]: { id: 39620, parent: 18467, channel: 'Restaurants', weight: 10 },
  [BzNewsChannel.RETAIL_SALES]: { id: 30777, parent: 57, channel: 'Retail Sales', weight: 7 },
  [BzNewsChannel.REVIEWS]: { id: 31781, parent: 0, channel: 'Reviews', weight: 73 },
  [BzNewsChannel.RUMORS]: { id: 17374, parent: 57, channel: 'Rumors', weight: 3 },
  [BzNewsChannel.SEC]: { id: 171552, parent: 0, channel: 'SEC', weight: 33 },
  [BzNewsChannel.SECTOR_ETFS]: { id: 49, parent: 47, channel: 'Sector ETFs', weight: 0 },
  [BzNewsChannel.SHORT_IDEAS]: { id: 39, parent: 22, channel: 'Short Ideas', weight: 1 },
  [BzNewsChannel.SHORT_SELLERS]: { id: 32789, parent: 0, channel: 'Short Sellers', weight: 0 },
  [BzNewsChannel.SIGNALS]: { id: 171557, parent: 0, channel: 'Signals', weight: 34 },
  [BzNewsChannel.SMALL_BUSINESS]: { id: 40436, parent: 0, channel: 'Small Business', weight: 30 },
  [BzNewsChannel.SMALL_CAP]: { id: 46411, parent: 57, channel: 'Small Cap', weight: 10 },
  [BzNewsChannel.SMALL_CAP_ANALYSIS]: { id: 42, parent: 22, channel: 'Small Cap Analysis', weight: 3 },
  [BzNewsChannel.SOCIAL_MEDIA]: { id: 831971, parent: 18467, channel: 'Social Media', weight: 0 },
  [BzNewsChannel.SPACE]: { id: 45040, parent: 18467, channel: 'SPACE', weight: 0 },
  [BzNewsChannel.SPECIALTY_ETFS]: { id: 52, parent: 47, channel: 'Specialty ETFs', weight: 2 },
  [BzNewsChannel.SPORTS]: { id: 413389, parent: 18467, channel: 'Sports', weight: 12 },
  [BzNewsChannel.SPORTS_BETTING]: { id: 831972, parent: 18467, channel: 'Sports Betting', weight: 0 },
  [BzNewsChannel.STARTUPS]: { id: 38927, parent: 0, channel: 'Startups', weight: 29 },
  [BzNewsChannel.STOCK_SPLIT]: { id: 66, parent: 57, channel: 'Stock Split', weight: 15 },
  [BzNewsChannel.SUCCESS_STORIES]: { id: 38926, parent: 0, channel: 'Success Stories', weight: 27 },
  [BzNewsChannel.TECH]: { id: 6, parent: 0, channel: 'Tech', weight: 57 },
  [BzNewsChannel.TECHNICALS]: { id: 16890, parent: 22, channel: 'Technicals', weight: 4 },
  [BzNewsChannel.TERMINATION]: { id: 66318, parent: 67, channel: 'Termination', weight: 1 },
  [BzNewsChannel.TOP_STORIES]: { id: 138079, parent: 0, channel: 'Top Stories', weight: 24 },
  [BzNewsChannel.TOPICS]: { id: 17, parent: 18467, channel: 'Topics', weight: 8 },
  [BzNewsChannel.TRADING_IDEAS]: { id: 22, parent: 0, channel: 'Trading Ideas', weight: 66 },
  [BzNewsChannel.TRAVEL]: { id: 18468, parent: 18467, channel: 'Travel', weight: 9 },
  [BzNewsChannel.TREASURIES]: { id: 34990, parent: 57, channel: 'Treasuries', weight: 18 },
  [BzNewsChannel.UPGRADES]: { id: 69, parent: 67, channel: 'Upgrades', weight: 2 },
  [BzNewsChannel.WIIM]: { id: 726669, parent: 0, channel: 'WIIM', weight: 0 },
};

// Lookup map for channel string -> object
export const BZ_NEWS_CHANNELS_MAP: Record<string, BzNewsChannelItem> = Object.fromEntries(
  Object.entries(BZ_NEWS_CHANNELS).map(([key, obj]) => [key, obj])
);
