import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

// Define the collections that should have standard access
const STANDARD_COLLECTIONS = [
  'company-data',
  'market-data',
  'tracked-symbols',
  'economics',
  'news',
  'time-series',
  // Add more collections here as needed
] as const;

// Define the output path for the generated rules
const RULES_PATH = join(__dirname, '..', 'firestore.rules');

// Template for the Firestore rules
const RULES_TEMPLATE = (collections: string[]) => `// This file is auto-generated by scripts/generate-rules.ts
// Do not edit this file directly - update the script and regenerate

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    // Helper functions
    function isAuthenticated() {
      return request.auth != null;
    }
    
    function isBackend() {
      return isAuthenticated() && (
        request.auth.token.firebase.sign_in_provider == 'function' ||
        (request.query.debug == true && request.auth.token.firebase.sign_in_provider == 'debug')
      );
    }

    // Auto-generated list of standard collections
    function getStandardCollections() {
      return [
        ${collections.map(c => `'${c}'`).join(',\n        ')}
      ];
    }

    function isStandardCollection(collection) {
      return getStandardCollections().hasAny([collection]);
    }

    // Standard access pattern for all top-level collections
    match /{collection}/{document=**} {
      allow read: if isAuthenticated() && isStandardCollection(collection);
      allow write: if isBackend() && isStandardCollection(collection);
    }

    // Test collection - more permissive rules for debugging
    match /test_collection/{document} {
      allow read, write: if isAuthenticated();
    }
  }
}`;

// Create the scripts directory if it doesn't exist
const SCRIPTS_DIR = join(__dirname);
if (!existsSync(SCRIPTS_DIR)) {
  mkdirSync(SCRIPTS_DIR, { recursive: true });
}

// Generate and write the rules
const generatedRules = RULES_TEMPLATE(STANDARD_COLLECTIONS);
writeFileSync(RULES_PATH, generatedRules);

console.log(`✅ Firestore rules generated at: ${RULES_PATH}`);
console.log(`Collections included: ${STANDARD_COLLECTIONS.join(', ')}`);
